package gamedata;

import java.util.List;
import java.util.Map;

/**
 * Holds all the data that is encoded for a level
 * such as:
 * 1) Enemies
 * 2) Preferences (e.g., waves of attack)
 * 3) Difficulty
 * 4) Duration of enemy attack
 * 5) Health, attack and speed multipliers
 * (more of each with higher levels)
 * 
 * Generated by the Game Authoring Environment and
 * invoked in the GameController when 
 * new LevelControllers are created.
 * 
 * @author maddiebriere
 *
 */
public class LevelData {
	private PreferencesData myPreferences;
	
	//TODO Upgrade to list later -- single wave for now
	private WaveData myEnemyWave;
	private int difficulty;
	private double duration; //duration for enemy presence
	
	//Increase by level
	private double healthMultiplier;
	private double attackMultiplier;
	private double speedMultiplier;

	public LevelData(double duration){
		this.duration = duration;
	}
	
	public void addEnemyWave(ActorData actor, Integer number, List<Integer> myPaths){
		myEnemyWave.addEnemyWave(new EnemyWaveData(actor, number, myPaths));
	}

	public PreferencesData getMyPreferences() {
		return myPreferences;
	}

	public void setMyPreferences(PreferencesData myPreferences) {
		this.myPreferences = myPreferences;
	}

	public Map<ActorData, Integer> getTroops() {
		return myEnemyWave
	}

	public void setTroops(Map<ActorData, Integer> troops) {
		this.troops = troops;
	}

	public int getDifficulty() {
		return difficulty;
	}

	public void setDifficulty(int difficulty) {
		this.difficulty = difficulty;
	}

	public double getDuration() {
		return duration;
	}

	public void setDuration(double duration) {
		this.duration = duration;
	}

	public double getHealthMultiplier() {
		return healthMultiplier;
	}

	public void setHealthMultiplier(double healthMultiplier) {
		this.healthMultiplier = healthMultiplier;
	}

	public double getAttackMultiplier() {
		return attackMultiplier;
	}

	public void setAttackMultiplier(double attackMultiplier) {
		this.attackMultiplier = attackMultiplier;
	}

	public double getSpeedMultiplier() {
		return speedMultiplier;
	}

	public void setSpeedMultiplier(double speedMultiplier) {
		this.speedMultiplier = speedMultiplier;
	}
	
	
	
}
