package gamedata;

import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Holds all the data that is encoded for a level
 * such as:
 * 1) Enemies
 * 2) Preferences (e.g., waves of attack)
 * 3) Difficulty
 * 4) Duration of enemy attack
 * 5) Health, attack and speed multipliers
 * (more of each with higher levels)
 * 
 * Generated by the Game Authoring Environment and
 * invoked in the GameController when 
 * new LevelControllers are created.
 * 
 * @author maddiebriere
 *
 */
public class LevelData {
	private PreferencesData myPreferences;
	
	//TODO Upgrade to list later -- single wave for now
	private WaveData myEnemyWave;
	private double difficulty;
	private double duration; 
	
	private final double DEFAULT = 1;
	
	//Increase by level
	private Optional<Double> healthMultiplier;
	private Optional<Double> attackMultiplier;
	private Optional<Double> speedMultiplier;

	public LevelData(double duration){
		this.duration = duration;
	}
	
	/**
	 * Add an enemy type (ActorData) with a number representing its frequency (E.g., 50 Goblins) 
	 * and a List of available Paths for that enemy, corresponding to numbers (these numbers
	 * can be retrieved via the PathData in GameData or using the getPathOptions method in GameData).
	 * 
	 * Assumption: There is only a single wave for sprint #1
	 * 
	 * @param actor ActorData representing enemy
	 * @param number Number of the enemy (E.g., 50 attackers)
	 * @param myPaths The possible paths this enemy can take
	 */
	public void addWaveEnemy(ActorData actor, Integer number, List<Integer> myPaths){
		myEnemyWave.addWaveEnemy(new EnemyInWaveData(actor, number, myPaths));
	}
	
	//TODO: Add remove function

	public PreferencesData getMyPreferences() {
		return myPreferences;
	}

	public void setMyPreferences(PreferencesData myPreferences) {
		this.myPreferences = myPreferences;
	}

	/**
	 * Assumed single wave right now (for first sprint), retrieve all of the enemies attacking
	 * in this wave, in the form of EnemyInWaveData objects.
	 * 
	 * @return A List of EnemyInWaveData objects, each which holds an ActorData, Integer 
	 * (frequency) and List of paths.
	 */
	public List<EnemyInWaveData> getTroops() {
		return myEnemyWave.getWaveEnemies();
	}

	public double getDifficulty() {
		return difficulty;
	}

	public double getDuration() {
		return duration;
	}

	public void setDuration(double duration) {
		this.duration = duration;
	}

	public double getHealthMultiplier() {
		return healthMultiplier.orElse(DEFAULT);
	}

	public void setHealthMultiplier(Optional<Double> healthMultiplier) {
		this.healthMultiplier = healthMultiplier;
	}

	public double getAttackMultiplier() {
		return attackMultiplier.orElse(DEFAULT);
	}

	public void setAttackMultiplier(Optional<Double> attackMultiplier) {
		this.attackMultiplier = attackMultiplier;
	}

	public double getSpeedMultiplier() {
		return speedMultiplier.orElse(DEFAULT);
	}

	public void setSpeedMultiplier(Optional<Double> speedMultiplier) {
		this.speedMultiplier = speedMultiplier;
	}

	public void setDifficulty(double d) {
		difficulty = d;
	}
	
	
	
}
